apiVersion: networking.gke.io/v1
kind: GCPAuthzPolicy
metadata:
  name: "test"
spec:
  action: CUSTOM
  httpRules:
  - to:
      operations:
      - paths:
        - type: Exact
          value: "/"
  targetRefs:
  - kind: Deployment
    name: test-deploy
    group: ""
