apiVersion: networking.gke.io/v1
kind: GCPAuthzPolicy
metadata:
  name: "test"
spec:
  action: DENY
  httpRules:
  - to:
      operations:
      - paths:
        - type: Exact
          value: "/"
  customProviders:
    cloudIAP: true
  targetRefs:
  - kind: Deployment
    name: test-deploy
    group: ""
