apiVersion: networking.gke.io/v1
kind: GCPAuthzExtension
metadata:
  name: "test"
spec:
  backendRef:
    group: ""
    kind: Service
    name: test-service
    port: 80
  authority: hello.com
  timeout: 1s
  failOpen: true
  metadata:
    "key": "value"
  forwardHeaders:
  - hello.com
  wireFormat: ExtProcGRPC
