apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereami-routes
  namespace: multi-cluster-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whereami-routes
  template:
    metadata:
      labels:
        app: whereami-routes
    spec:
      containers:
      - name: whereami-routes
        image: gcr.io/google-samples/whereami:v1.1.2
        env:
        - name: METADATA
          value: "default-backend"
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: whereami-routes
  namespace: multi-cluster-demo
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: whereami-routes