apiVersion: v1
kind: Namespace
metadata:
  name: multi-cluster-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whereami
  namespace: multi-cluster-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whereami
  template:
    metadata:
      labels:
        app: whereami
    spec:
      containers:
      - name: whereami
        image: us-docker.pkg.dev/google-samples/containers/gke/whereami:v1.2.20
        env:
        - name: METADATA
          value: "default-backend"
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP
---
apiVersion: v1
kind: Service
metadata:
  name: whereami
  namespace: multi-cluster-demo
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: whereami