apiVersion: v1
kind: Namespace
metadata:
  name: multi-cluster-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo
  namespace: multi-cluster-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foo
  template:
    metadata:
      labels:
        app: foo
        version: v1
    spec:
      containers:
      - name: whereami
        image: gcr.io/alexmattson-scratch/whereami
        ports:
          - name: http
            containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bar
  namespace: multi-cluster-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bar
  template:
    metadata:
      labels:
        app: bar
        version: v1
    spec:
      containers:
      - name: whereami
        image: gcr.io/alexmattson-scratch/whereami
        ports:
          - name: http
            containerPort: 8080
---