apiVersion: networking.gke.io/v1
kind: GCPAuthzExtension
metadata:
  name: "test"
spec:
  backendRef:
    group: "fake-group"
    kind: Service
    name: test-service
    port: 80
  authority: hello.com
