apiVersion: v1
kind: Namespace
metadata:
  name: multi-cluster-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: default-backend
  namespace: multi-cluster-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: default-backend
  template:
    metadata:
      labels:
        app: default-backend
    spec:
      containers:
      - name: whereami
        image: gcr.io/google-samples/whereami:v1.1.2
        env:
        - name: METADATA
          value: "default-backend"
        ports:
          - name: http
            containerPort: 8080
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
            scheme: HTTP