apiVersion: v1
kind: Service
metadata:
  name: wheraami-ilb
  annotations:
    cloud.google.com/load-balancer-type: Internal
  labels:
    app: wheraami-ilb
  namespace: multi-cluster-demo
spec:
  type: LoadBalancer
  loadBalancerIP: 10.138.1.20
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: whereami
