##################################################
# Referenced by https://cloud.google.com/kubernetes-engine/docs/how-to/horizontal-pod-autoscaling#autoscale-traffic
##################################################

apiVersion: apps/v1
kind: Deployment
metadata:
  name: store-autoscale
spec:
  replicas: 2
  selector:
    matchLabels:
      app: store-autoscale
  template:
    metadata:
      labels:
        app: store-autoscale
    spec:
      containers:
      - name: whereami
        image: us-docker.pkg.dev/google-samples/containers/gke/whereami:v1.2.20
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: store-autoscale
spec:
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  selector:
    app: store-autoscale
  type: ClusterIP
---
apiVersion: networking.gke.io/v1
kind: GCPBackendPolicy
metadata:
  name: store-autoscale
spec:
  default:
    maxRatePerEndpoint: 10
  targetRef:
    group: ""
    kind: Service
    name: store-autoscale
---
kind: Gateway
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: store-autoscale
spec:
  gatewayClassName: gke-l7-gxlb
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: store-autoscale
  labels:
    gateway: store-autoscale
spec:
  parentRefs:
  - name: store-autoscale
  rules:
  - backendRefs:
    - name: store-autoscale
      port: 8080
